server {
    listen 80;
    client_max_body_size 120m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_request_buffering off;
    }

    location /player/ {
        alias /usr/share/nginx/player/;
        try_files $uri $uri/ /player/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
